# <font color='blue'>Data Science Academy</font>
# <font color='blue'>Análise de Dados com Linguagem Python</font>

## Laboratório Prático - Label Encoding

In [2]:
# Imports
import pandas as pd
import datetime

In [20]:
# Extrai a data atual do sistema
# O código data_atual = datetime.datetime.now() faz o seguinte:

# 1. datetime.datetime
#    - Aqui estamos acessando a classe "datetime" dentro do módulo "datetime".
#    - Essa classe representa objetos de data e hora (com ano, mês, dia, hora, minuto, segundo).

# 2. .now()
#    - O método .now() retorna a data e hora atuais do sistema (momento em que o código é executado).
#    - Inclui ano, mês, dia, hora, minuto, segundo e microsegundos.

# 3. data_atual = ...
#    - Armazena o resultado (um objeto datetime) na variável "data_atual".
#    - Exemplo: Se o código for executado em 08/03/2026 às 14:45:30,
#      então data_atual = datetime.datetime(2026, 3, 8, 14, 45, 30, ...)

# -----------------------------
# Interpretação prática:
# Esse comando captura a data e hora atuais do sistema.
# É útil para registrar logs, marcar eventos, calcular diferenças de tempo
# ou simplesmente mostrar ao usuário o momento da execução.
data_atual = datetime.datetime.now()

In [21]:
data_atual

datetime.datetime(2026, 3, 8, 14, 46, 35, 817533)

In [9]:
# Vamos gerar um range de datas dos 20 anteriores à data atual
# O código date_list = [data_atual - datetime.timedelta(days = x) for x in range(0,20)] faz o seguinte:

# 1. range(0,20)
#    - Cria uma sequência de números inteiros de 0 até 19.
#    - Esses números serão usados para representar a quantidade de dias a subtrair.

# 2. datetime.timedelta(days = x)
#    - Cria um objeto "timedelta" que representa uma diferença de tempo.
#    - Aqui, cada "x" é um número de dias.
#    - Exemplo: datetime.timedelta(days=5) representa um intervalo de 5 dias.

# 3. data_atual - datetime.timedelta(days = x)
#    - Subtrai o intervalo de tempo (timedelta) da data atual.
#    - Isso gera uma data anterior à data_atual, retrocedendo "x" dias.
#    - Exemplo: Se data_atual = 08/03/2026 e x=3,
#               então resultado = 05/03/2026.

# 4. [ ... for x in range(0,20) ]
#    - É uma list comprehension.
#    - Para cada valor de x de 0 até 19, calcula data_atual - timedelta(days=x).
#    - Gera uma lista com 20 datas, indo da data atual até 19 dias atrás.

# 5. date_list = ...
#    - Armazena essa lista na variável "date_list".
#    - Exemplo: Se data_atual = 08/03/2026,
#               então date_list conterá:
#               [08/03/2026, 07/03/2026, 06/03/2026, ..., 18/02/2026]

# -----------------------------
# Interpretação prática:
# Esse comando cria uma lista com as últimas 20 datas (incluindo hoje).
# É útil para análises temporais, como gerar séries de datas para relatórios,
# gráficos de tendência ou simulações de dados históricos.
date_list = [data_atual - datetime.timedelta(days = x) for x in range(0,20) ]

In [10]:
date_list

[datetime.datetime(2026, 3, 8, 14, 15, 28, 39922),
 datetime.datetime(2026, 3, 7, 14, 15, 28, 39922),
 datetime.datetime(2026, 3, 6, 14, 15, 28, 39922),
 datetime.datetime(2026, 3, 5, 14, 15, 28, 39922),
 datetime.datetime(2026, 3, 4, 14, 15, 28, 39922),
 datetime.datetime(2026, 3, 3, 14, 15, 28, 39922),
 datetime.datetime(2026, 3, 2, 14, 15, 28, 39922),
 datetime.datetime(2026, 3, 1, 14, 15, 28, 39922),
 datetime.datetime(2026, 2, 28, 14, 15, 28, 39922),
 datetime.datetime(2026, 2, 27, 14, 15, 28, 39922),
 datetime.datetime(2026, 2, 26, 14, 15, 28, 39922),
 datetime.datetime(2026, 2, 25, 14, 15, 28, 39922),
 datetime.datetime(2026, 2, 24, 14, 15, 28, 39922),
 datetime.datetime(2026, 2, 23, 14, 15, 28, 39922),
 datetime.datetime(2026, 2, 22, 14, 15, 28, 39922),
 datetime.datetime(2026, 2, 21, 14, 15, 28, 39922),
 datetime.datetime(2026, 2, 20, 14, 15, 28, 39922),
 datetime.datetime(2026, 2, 19, 14, 15, 28, 39922),
 datetime.datetime(2026, 2, 18, 14, 15, 28, 39922),
 datetime.datetime(2026, 2, 17, 14, 15, 28, 39922)]

In [11]:
# Convertemos a lista em um dataframe
df = pd.DataFrame(date_list)

In [12]:
df.head()

                           0
0 2026-03-08 14:15:28.039922
1 2026-03-07 14:15:28.039922
2 2026-03-06 14:15:28.039922
3 2026-03-05 14:15:28.039922
4 2026-03-04 14:15:28.039922

In [13]:
# Ajusta o nome da coluna
df.columns = ['data']

In [14]:
df.head()

                        data
0 2026-03-08 14:15:28.039922
1 2026-03-07 14:15:28.039922
2 2026-03-06 14:15:28.039922
3 2026-03-05 14:15:28.039922
4 2026-03-04 14:15:28.039922

In [15]:
# Extraímos os dias da semana
# O código df['dia_da_semana'] = df['data'].dt.day_name() faz o seguinte:

# 1. df['data']
#    - Acessa a coluna chamada "data" do DataFrame "df".
#    - Essa coluna deve estar no formato datetime (datas e horas).
#    - Caso contrário, seria necessário converter antes com pd.to_datetime().

# 2. .dt
#    - O atributo .dt permite acessar propriedades específicas de objetos datetime
#      dentro de uma Series do pandas.
#    - Exemplo: .dt.year retorna o ano, .dt.month retorna o mês, .dt.day retorna o dia.

# 3. .day_name()
#    - Retorna o nome do dia da semana correspondente a cada data.
#    - Exemplo: Se a data for 2026-03-08, o resultado será "Sunday".
#    - Se a data for 2026-03-09, o resultado será "Monday".

# 4. df['dia_da_semana'] = ...
#    - Cria uma nova coluna chamada "dia_da_semana" no DataFrame.
#    - Essa coluna recebe os nomes dos dias da semana correspondentes às datas da coluna "data".

# -----------------------------
# Exemplo prático:
# Se df['data'] = [2026-03-08, 2026-03-09, 2026-03-10]
# então df['dia_da_semana'] = ["Sunday", "Monday", "Tuesday"]

# -----------------------------
# Interpretação prática:
# Esse comando adiciona ao DataFrame uma informação categórica útil:
# o dia da semana de cada registro. Isso pode ser usado em análises temporais,
# como verificar padrões de comportamento em determinados dias (ex: vendas maiores aos sábados).
df['dia_da_semana'] = df['data'].dt.day_name()

In [16]:
df

                         data dia_da_semana
0  2026-03-08 14:15:28.039922        Sunday
1  2026-03-07 14:15:28.039922      Saturday
2  2026-03-06 14:15:28.039922        Friday
3  2026-03-05 14:15:28.039922      Thursday
4  2026-03-04 14:15:28.039922     Wednesday
5  2026-03-03 14:15:28.039922       Tuesday
6  2026-03-02 14:15:28.039922        Monday
7  2026-03-01 14:15:28.039922        Sunday
8  2026-02-28 14:15:28.039922      Saturday
9  2026-02-27 14:15:28.039922        Friday
10 2026-02-26 14:15:28.039922      Thursday
11 2026-02-25 14:15:28.039922     Wednesday
12 2026-02-24 14:15:28.039922       Tuesday
13 2026-02-23 14:15:28.039922        Monday
14 2026-02-22 14:15:28.039922        Sunday
15 2026-02-21 14:15:28.039922      Saturday
16 2026-02-20 14:15:28.039922        Friday
17 2026-02-19 14:15:28.039922      Thursday
18 2026-02-18 14:15:28.039922     Wednesday
19 2026-02-17 14:15:28.039922       Tuesday

In [17]:
# Criamos um dicionário mapeando dia da semana com um número correspondente
# Obs: se o seu sistema estiver em português e se for necessário, use os dias da semana em português
dict_dia_semana = {'Monday':1, 
                   "Tuesday":2,
                   "Wednesday":3,
                   "Thursday":4,
                   "Friday":5,
                   "Saturday":6,
                   "Sunday":7}

In [18]:
# Label Encode - Substituímos o nome da semana pelo número correspondente
# O código df['dia_semana_cod'] = df['dia_da_semana'].map(dict_dia_semana) faz o seguinte:

# 1. df['dia_da_semana']
#    - Acessa a coluna "dia_da_semana" do DataFrame "df".
#    - Essa coluna contém os nomes dos dias da semana (ex: "Monday", "Tuesday", etc.).

# 2. dict_dia_semana
#    - É um dicionário previamente definido que mapeia cada nome de dia da semana
#      para um código numérico.
#    - Exemplo: {"Monday": 0, "Tuesday": 1, "Wednesday": 2, ...}

# 3. .map(dict_dia_semana)
#    - O método .map() substitui cada valor da coluna "dia_da_semana"
#      pelo valor correspondente no dicionário dict_dia_semana.
#    - Exemplo: Se df['dia_da_semana'] = ["Monday", "Tuesday", "Monday"]
#               e dict_dia_semana = {"Monday": 0, "Tuesday": 1}
#               então o resultado será [0, 1, 0].

# 4. df['dia_semana_cod'] = ...
#    - Cria uma nova coluna chamada "dia_semana_cod" no DataFrame.
#    - Essa coluna recebe os códigos numéricos correspondentes aos dias da semana.

# -----------------------------
# Interpretação prática:
# Esse comando transforma os nomes dos dias da semana em números.
# É uma forma de aplicar **encoding** em variáveis categóricas,
# permitindo que algoritmos de Machine Learning processem essa informação
# sem precisar lidar diretamente com strings.
df['dia_semana_cod'] = df['dia_da_semana'].map(dict_dia_semana)

In [19]:
df

                         data dia_da_semana  dia_semana_cod
0  2026-03-08 14:15:28.039922        Sunday               7
1  2026-03-07 14:15:28.039922      Saturday               6
2  2026-03-06 14:15:28.039922        Friday               5
3  2026-03-05 14:15:28.039922      Thursday               4
4  2026-03-04 14:15:28.039922     Wednesday               3
5  2026-03-03 14:15:28.039922       Tuesday               2
6  2026-03-02 14:15:28.039922        Monday               1
7  2026-03-01 14:15:28.039922        Sunday               7
8  2026-02-28 14:15:28.039922      Saturday               6
9  2026-02-27 14:15:28.039922        Friday               5
10 2026-02-26 14:15:28.039922      Thursday               4
11 2026-02-25 14:15:28.039922     Wednesday               3
12 2026-02-24 14:15:28.039922       Tuesday               2
13 2026-02-23 14:15:28.039922        Monday               1
14 2026-02-22 14:15:28.039922        Sunday               7
15 2026-02-21 14:15:28.039922      Saturday               6
16 2026-02-20 14:15:28.039922        Friday               5
17 2026-02-19 14:15:28.039922      Thursday               4
18 2026-02-18 14:15:28.039922     Wednesday               3
19 2026-02-17 14:15:28.039922       Tuesday               2

# Fim