# <font color='blue'>Data Science Academy</font>
# <font color='blue'>Análise de Dados com Linguagem Python</font>

## <font color='blue'>Projeto 5</font>
## <font color='blue'>Análise de Dados Para Traçar Estratégias de Crescimento e Retenção da Base de Clientes</font>

![title](imagens/Projeto5.png)

## Pré-Requisitos

Recomendamos que você tenha concluído pelo menos os 5 primeiros capítulos do curso gratuito de <a href="https://www.datascienceacademy.com.br/course?courseid=python-fundamentos">Python Fundamentos Para Análise de Dados</a>. Recomendamos ainda o capítulo sobre Machine Learning nesse mesmo curso.

## Instalando e Carregando os Pacotes

In [1]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.8.20

In [3]:
# Para atualizar um pacote, execute o comando abaixo no terminal ou prompt de comando:
# pip install -U nome_pacote
#%pip install -U scikit-learn
 

# Para instalar a versão exata de um pacote, execute o comando abaixo no terminal ou prompt de comando:
# !pip install nome_pacote==versão_desejada

# Depois de instalar ou atualizar o pacote, reinicie o jupyter notebook.

# Instala o pacote watermark. 
# Esse pacote é usado para gravar as versões de outros pacotes usados neste jupyter notebook.
# !pip install -q -U watermark

In [4]:
# Imports
# Imports
# import pandas as pd        # Biblioteca para manipulação e análise de dados em formato de tabelas (DataFrames).
# import numpy as np         # Biblioteca para cálculos numéricos e operações com arrays, muito usada em ciência de dados.
# from sklearn import linear_model  # Importa modelos de regressão linear da biblioteca scikit-learn (Machine Learning).
# import warnings            # Biblioteca para gerenciar mensagens de aviso durante a execução do código.
# warnings.filterwarnings("ignore")  # Ignora avisos (warnings) para deixar a saída mais limpa e focada nos resultados.


import pandas as pd
import numpy as np
from sklearn import linear_model
import warnings
warnings.filterwarnings("ignore")

In [5]:
# Versões dos pacotes usados neste jupyter notebook
# %reload_ext watermark  
# Recarrega a extensão "watermark" no Jupyter Notebook.
# Essa extensão serve para exibir informações sobre o ambiente, como autor, data e versões de pacotes.

# %watermark -a "Data Science Academy" --iversions  
# Exibe um "carimbo" (watermark) com:
#   - O autor definido como "Data Science Academy".
#   - As versões das bibliotecas atualmente importadas (--iversions).
# Isso ajuda a documentar o ambiente de execução, garantindo reprodutibilidade.

%reload_ext watermark
%watermark -a "Data Science Academy" --iversions

Author: Data Science Academy

numpy   : 1.21.0
pandas  : 1.3.3
platform: 1.0.8
sklearn : 1.3.2

## Carregando os Dados

In [6]:
# Carrega os dados
dados = pd.read_csv('dados/dataset.csv')

In [7]:
# Shape
dados.shape

(13, 4)

In [8]:
# Visualiza os dados
dados

                      Modelo  Kilometragem  Preco_Venda  Idade_Veiculo
0            Jaguar F-Type R         69000        18000              6
1            Jaguar F-Type R         35000        34000              3
2            Jaguar F-Type R         57000        26100              5
3            Jaguar F-Type R         22500        40000              2
4            Jaguar F-Type R         46000        31500              4
5             Mustang Mach 1         59000        29400              5
6             Mustang Mach 1         52000        32000              5
7             Mustang Mach 1         72000        19300              6
8             Mustang Mach 1         91000        12000              8
9   Mercedez Benz AMG GLE 53         67000        22000              6
10  Mercedez Benz AMG GLE 53         83000        20000              7
11  Mercedez Benz AMG GLE 53         79000        21000              7
12  Mercedez Benz AMG GLE 53         59000        33000              5

In [9]:
# Tipos de dados
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Modelo         13 non-null     object
 1   Kilometragem   13 non-null     int64
 2   Preco_Venda    13 non-null     int64
 3   Idade_Veiculo  13 non-null     int64
dtypes: int64(3), object(1)
memory usage: 544.0+ bytes

> Pergunta: Para a variável categórica (object) no dataset, qual técnica de encoding devemos aplicar? Justifique sua resposta.

## Aplicando One-Hot-Encoding

https://pandas.pydata.org/docs/reference/api/pandas.get_dummies.html

In [10]:
# Dataset original
dados

                      Modelo  Kilometragem  Preco_Venda  Idade_Veiculo
0            Jaguar F-Type R         69000        18000              6
1            Jaguar F-Type R         35000        34000              3
2            Jaguar F-Type R         57000        26100              5
3            Jaguar F-Type R         22500        40000              2
4            Jaguar F-Type R         46000        31500              4
5             Mustang Mach 1         59000        29400              5
6             Mustang Mach 1         52000        32000              5
7             Mustang Mach 1         72000        19300              6
8             Mustang Mach 1         91000        12000              8
9   Mercedez Benz AMG GLE 53         67000        22000              6
10  Mercedez Benz AMG GLE 53         83000        20000              7
11  Mercedez Benz AMG GLE 53         79000        21000              7
12  Mercedez Benz AMG GLE 53         59000        33000              5

In [11]:
# Obtém as variáveis dummy
# df_dummies = pd.get_dummies(dados['Modelo'])
# Cria variáveis dummies (One-Hot Encoding) a partir da coluna "Modelo" do DataFrame "dados".
# Cada categoria distinta em "Modelo" vira uma nova coluna binária (0 ou 1).
# Exemplo: se "Modelo" tiver valores ["A", "B", "A", "C"],
# o resultado será um DataFrame com colunas "A", "B", "C",
# onde cada linha indica com 1 ou 0 se pertence àquela categoria.
#
# O resultado é armazenado em "df_dummies", que será um DataFrame
# contendo apenas as colunas dummies referentes à variável "Modelo".
df_dummies = pd.get_dummies(dados['Modelo'])

In [12]:
# Variáveis dummy
df_dummies

    Jaguar F-Type R  Mercedez Benz AMG GLE 53  Mustang Mach 1
0                 1                         0               0
1                 1                         0               0
2                 1                         0               0
3                 1                         0               0
4                 1                         0               0
5                 0                         0               1
6                 0                         0               1
7                 0                         0               1
8                 0                         0               1
9                 0                         1               0
10                0                         1               0
11                0                         1               0
12                0                         1               0

In [13]:
# Concatenamos os dataframes
# df = pd.concat([dados, df_dummies], axis='columns')
# Concatena (junta) o DataFrame original "dados" com o DataFrame "df_dummies".
# O parâmetro axis='columns' indica que a junção será feita pelas colunas (lado a lado).
# Assim, o resultado "df" terá todas as colunas originais de "dados"
# mais as colunas dummies criadas a partir da variável "Modelo".
#
# Exemplo:
# Se "dados" tinha colunas [ID, Modelo] e "df_dummies" tinha colunas [A, B, C],
# então "df" terá colunas [ID, Modelo, A, B, C].

df = pd.concat([dados, df_dummies], axis = 'columns')

In [14]:
df

,Modelo,Kilometragem,Preco_Venda,Idade_Veiculo,Jaguar F-Type R,Mercedez Benz AMG GLE 53,Mustang Mach 1
0,Jaguar F-Type R,69000,18000,6,1,0,0
1,Jaguar F-Type R,35000,34000,3,1,0,0
2,Jaguar F-Type R,57000,26100,5,1,0,0
3,Jaguar F-Type R,22500,40000,2,1,0,0
4,Jaguar F-Type R,46000,31500,4,1,0,0
5,Mustang Mach 1,59000,29400,5,0,0,1
6,Mustang Mach 1,52000,32000,5,0,0,1
7,Mustang Mach 1,72000,19300,6,0,0,1
8,Mustang Mach 1,91000,12000,8,0,0,1
9,Mercedez Benz AMG GLE 53,67000,22000,6,0,1,0
10,Mercedez Benz AMG GLE 53,83000,20000,7,0,1,0
11,Mercedez Benz AMG GLE 53,79000,21000,7,0,1,0
12,Mercedez Benz AMG GLE 53,59000,33000,5,0,1,0

In [15]:
# Drop da coluna categórica
# newdf = df.drop(['Modelo'], axis=1)
# Cria um novo DataFrame chamado "newdf" a partir de "df",
# removendo a coluna "Modelo".
#
# O parâmetro axis=1 indica que a remoção será feita em colunas (não em linhas).
# Assim, "newdf" terá todas as colunas originais de "df" exceto "Modelo".
#
# Isso é útil porque já transformamos "Modelo" em variáveis dummies,
# então a coluna original categórica não é mais necessária para análise ou modelagem.
newdf = df.drop(['Modelo'], axis = 1)

In [16]:
newdf

,Kilometragem,Preco_Venda,Idade_Veiculo,Jaguar F-Type R,Mercedez Benz AMG GLE 53,Mustang Mach 1
0,69000,18000,6,1,0,0
1,35000,34000,3,1,0,0
2,57000,26100,5,1,0,0
3,22500,40000,2,1,0,0
4,46000,31500,4,1,0,0
5,59000,29400,5,0,0,1
6,52000,32000,5,0,0,1
7,72000,19300,6,0,0,1
8,91000,12000,8,0,0,1
9,67000,22000,6,0,1,0
10,83000,20000,7,0,1,0
11,79000,21000,7,0,1,0
12,59000,33000,5,0,1,0

In [17]:
# Define os valores de X
# x = newdf.drop('Preco_Venda', axis=1)
# Cria um novo DataFrame chamado "x" a partir de "newdf",
# removendo a coluna "Preco_Venda".
#
# O parâmetro axis=1 indica que a remoção será feita em colunas (não em linhas).
# Assim, "x" conterá todas as variáveis independentes (features),
# enquanto "Preco_Venda" será tratada separadamente como variável alvo (y).
#
# Esse passo é típico em projetos de Machine Learning:
# - "x" → conjunto de variáveis explicativas (inputs).
# - "y" → variável que queremos prever (output).

x = newdf.drop('Preco_Venda', axis = 1)
x

,Kilometragem,Idade_Veiculo,Jaguar F-Type R,Mercedez Benz AMG GLE 53,Mustang Mach 1
0,69000,6,1,0,0
1,35000,3,1,0,0
2,57000,5,1,0,0
3,22500,2,1,0,0
4,46000,4,1,0,0
5,59000,5,0,0,1
6,52000,5,0,0,1
7,72000,6,0,0,1
8,91000,8,0,0,1
9,67000,6,0,1,0
10,83000,7,0,1,0
11,79000,7,0,1,0
12,59000,5,0,1,0

In [18]:
# Define os valores de y
# y = newdf['Preco_Venda']
# Cria a variável alvo (y) a partir da coluna "Preco_Venda" do DataFrame "newdf".
# Essa coluna contém os valores que queremos prever (preço de venda).
#
# Agora temos:
#   - x → conjunto de variáveis independentes (features), ou seja, os atributos que explicam o preço.
#   - y → variável dependente (target), ou seja, o preço de venda que será previsto pelo modelo.
#
# Esse é o padrão em projetos de Machine Learning:
#   x = dados de entrada
#   y = saída/resultado que queremos estimar

y = newdf['Preco_Venda']
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Preco_Venda, dtype: int64

In [19]:
# Cria o modelo
# modelo_v1 = linear_model.LinearRegression()
# Cria uma instância do modelo de Regressão Linear da biblioteca scikit-learn.
# Esse modelo será usado para aprender a relação entre as variáveis independentes (x)
# e a variável dependente (y = Preco_Venda).
#
# A regressão linear busca ajustar uma linha (ou hiperplano, em múltiplas variáveis)
# que melhor explica os dados, minimizando os erros entre os valores previstos e os reais.
#
# "modelo_v1" agora é um objeto que pode ser treinado (fit) com os dados
# e depois usado para fazer previsões (predict).

modelo_v1 = linear_model.LinearRegression()

In [20]:
# Treina o modelo
# Aprendizado supervisionado em machine learning
# modelo_v1.fit(x, y)
# Treina (ajusta) o modelo de regressão linear "modelo_v1"
# usando os dados de entrada (x) e a variável alvo (y).
#
# O método .fit():
#   - Calcula os coeficientes da regressão linear.
#   - Encontra a linha/hiperplano que melhor explica a relação
#     entre as variáveis independentes (x) e o preço de venda (y).
#
# Depois desse passo, o modelo já está treinado e pronto para:
#   - Fazer previsões com .predict(x_novo).
#   - Consultar os coeficientes com .coef_ e o intercepto com .intercept_.

modelo_v1.fit(x,y)

LinearRegression()

In [21]:
# Previsões do modelo
# modelo_v1.predict(x)
# Usa o modelo de regressão linear já treinado (modelo_v1)
# para gerar previsões da variável alvo (Preço de Venda),
# com base nos dados de entrada (x).
#
# O método .predict():
#   - Aplica os coeficientes e o intercepto calculados no treinamento.
#   - Retorna um array com os valores previstos de "Preco_Venda"
#     para cada linha do DataFrame x.
#
# Em resumo: você obtém os preços de venda estimados pelo modelo
# a partir das variáveis explicativas (features) que estavam em x.

modelo_v1.predict(x)

array([18705.2723644 , 35286.78445645, 24479.19112468, 41245.76426391,
       29882.98779056, 28023.6135243 , 30614.46818502, 21879.57266964,
       12182.34562104, 26183.72387884, 18929.31674102, 20409.80511857,
       30477.15426156])

In [22]:
# Uma previsão
# modelo_v1.predict([[7000, 4, 0, 0, 1]])
# Faz uma previsão do preço de venda usando o modelo treinado.
# O método .predict() recebe uma lista com os valores das variáveis independentes (features).
#
# Nesse exemplo, os valores passados correspondem a uma única observação:
#   - 7000 → pode ser quilometragem, valor numérico ou outra variável contínua.
#   - 4    → pode ser número de portas, idade do carro, ou outra característica.
#   - 0, 0 → variáveis dummies (categorias que não se aplicam).
#   - 1    → variável dummy indicando a categoria ativa.
#
# O modelo aplica os coeficientes aprendidos no treinamento e retorna
# o valor previsto de "Preco_Venda" para essa combinação de atributos.
modelo_v1.predict([[7000,4,0,0,1]])

array([48602.41606011])

In [23]:
# Uma previsão
# modelo_v1.predict([[45000, 4, 0, 1, 0]])
# Faz uma previsão do preço de venda para uma nova observação,
# usando o modelo de regressão linear já treinado.
#
# Os valores dentro da lista representam as variáveis independentes (features):
#   - 45000 → pode ser quilometragem, idade ou outra variável contínua.
#   - 4     → pode ser número de portas, anos de uso, etc.
#   - 0, 1, 0 → variáveis dummies que indicam a categoria do "Modelo".
#
# O método .predict() aplica os coeficientes aprendidos e retorna
# o valor estimado de "Preco_Venda" para esse conjunto de características.
modelo_v1.predict([[45000,4,0,1,0]])

array([36991.31721061])

In [24]:
# Uma previsão
# modelo_v1.predict([[86000, 7, 1, 0, 0]])
# Faz uma previsão do preço de venda para uma nova observação,
# usando o modelo de regressão linear já treinado.
#
# Os valores dentro da lista representam as variáveis independentes (features):
#   - 86000 → valor contínuo (ex.: quilometragem, idade ou outra característica numérica).
#   - 7     → pode ser número de portas, anos de uso ou outra variável inteira.
#   - 1, 0, 0 → variáveis dummies que indicam a categoria do "Modelo".
#
# O método .predict() aplica os coeficientes aprendidos no treinamento
# e retorna o valor estimado de "Preco_Venda" para esse conjunto de atributos.
modelo_v1.predict([[86000,7,1,0,0]])

array([11080.74313219])

In [25]:
# Acurácia do modelo
# modelo_v1.score(x, y)
# Calcula o coeficiente de determinação R² do modelo de regressão linear.
#
# O método .score():
#   - Compara os valores previstos pelo modelo com os valores reais (y).
#   - Retorna o R², que mede a proporção da variância de "Preco_Venda"
#     explicada pelas variáveis independentes (x).
#
# Interpretação do R²:
#   - 1.0 → modelo perfeito (explica 100% da variância).
#   - 0.0 → modelo não explica nada além da média.
#   - Valores negativos → modelo pior que simplesmente usar a média.
modelo_v1.score(x,y)

0.9417050937281082

## Aplicando Label Encoding

https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html

In [26]:
from sklearn.preprocessing import LabelEncoder

In [27]:
# Cópia do dataframe original
df_car = dados

In [28]:
df_car

                      Modelo  Kilometragem  Preco_Venda  Idade_Veiculo
0            Jaguar F-Type R         69000        18000              6
1            Jaguar F-Type R         35000        34000              3
2            Jaguar F-Type R         57000        26100              5
3            Jaguar F-Type R         22500        40000              2
4            Jaguar F-Type R         46000        31500              4
5             Mustang Mach 1         59000        29400              5
6             Mustang Mach 1         52000        32000              5
7             Mustang Mach 1         72000        19300              6
8             Mustang Mach 1         91000        12000              8
9   Mercedez Benz AMG GLE 53         67000        22000              6
10  Mercedez Benz AMG GLE 53         83000        20000              7
11  Mercedez Benz AMG GLE 53         79000        21000              7
12  Mercedez Benz AMG GLE 53         59000        33000              5

In [29]:
# Cria o objeto encoder
# from sklearn.preprocessing import LabelEncoder

# le = LabelEncoder()
# Cria uma instância do LabelEncoder, que é uma ferramenta da biblioteca scikit-learn
# usada para transformar variáveis categóricas em valores numéricos.
#
# Funcionamento:
#   - Cada categoria distinta recebe um número inteiro.
#   - Exemplo: ["A", "B", "C", "A"] → [0, 1, 2, 0].
#
# Isso é útil quando você tem variáveis categóricas que não podem ser usadas
# diretamente em modelos de Machine Learning, mas precisam ser convertidas
# para uma representação numérica.
le = LabelEncoder()

In [30]:
# Aplica o encoder
# df_car['Modelo'] = le.fit_transform(df_car['Modelo'])
# Aplica o LabelEncoder na coluna "Modelo" do DataFrame "df_car".
# O método .fit_transform():
#   - "fit" → aprende todas as categorias únicas presentes em "Modelo".
#   - "transform" → substitui cada categoria por um número inteiro.
#
# Exemplo:
#   Se "Modelo" tiver valores ["Sedan", "SUV", "Hatch"],
#   o LabelEncoder pode atribuir:
#     Sedan → 0
#     SUV   → 1
#     Hatch → 2
#
# O resultado é que a coluna "Modelo" passa a conter apenas números,
# o que facilita o uso em algoritmos de Machine Learning que não aceitam texto.

df_car['Modelo'] = le.fit_transform(df_car['Modelo'])

In [31]:
df_car

    Modelo  Kilometragem  Preco_Venda  Idade_Veiculo
0        0         69000        18000              6
1        0         35000        34000              3
2        0         57000        26100              5
3        0         22500        40000              2
4        0         46000        31500              4
5        2         59000        29400              5
6        2         52000        32000              5
7        2         72000        19300              6
8        2         91000        12000              8
9        1         67000        22000              6
10       1         83000        20000              7
11       1         79000        21000              7
12       1         59000        33000              5

In [32]:
# Define os valores de X
# x = df_car[['Modelo', 'Kilometragem', 'Idade_Veiculo']].values
# Seleciona as colunas "Modelo", "Kilometragem" e "Idade_Veiculo" do DataFrame "df_car".
# O método .values converte esse subconjunto em um array NumPy.
#
# Resultado:
#   - "x" será um array bidimensional (matriz) contendo apenas os valores numéricos dessas colunas.
#   - Cada linha representa um carro (observação).
#   - Cada coluna representa uma característica (feature).
#
# Esse formato é o que os algoritmos de Machine Learning do scikit-learn esperam
# para treinar modelos: um array de features (x) e um vetor alvo (y).

x = df_car[['Modelo', 'Kilometragem', 'Idade_Veiculo']].values
x

array([[    0, 69000,     6],
       [    0, 35000,     3],
       [    0, 57000,     5],
       [    0, 22500,     2],
       [    0, 46000,     4],
       [    2, 59000,     5],
       [    2, 52000,     5],
       [    2, 72000,     6],
       [    2, 91000,     8],
       [    1, 67000,     6],
       [    1, 83000,     7],
       [    1, 79000,     7],
       [    1, 59000,     5]], dtype=int64)

In [33]:
# Define os valores de y
# y = df_car['Preco_Venda']
# Define a variável alvo (y) como a coluna "Preco_Venda" do DataFrame "df_car".
#
# Essa coluna contém os valores reais de preço de venda,
# que o modelo tentará prever a partir das variáveis independentes (x).
#
# Agora temos:
#   - x → matriz de features (Modelo, Kilometragem, Idade_Veiculo).
#   - y → vetor alvo (Preço de Venda).
#
# Esse é o formato padrão para treinar modelos de Machine Learning:
#   x = dados de entrada
#   y = saída/resultado esperado
y = df_car['Preco_Venda']
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Preco_Venda, dtype: int64

In [34]:
# Cria a versão 2 do modelo
# from sklearn import linear_model

#modelo_v2 = linear_model.LinearRegression()
# Cria uma nova instância de regressão linear chamada "modelo_v2".
#
# Esse objeto é independente do "modelo_v1" que você criou antes.
# Isso significa que você pode treinar "modelo_v2" com outro conjunto de dados
# ou com uma versão diferente do DataFrame, sem interferir no primeiro modelo.
#
# A regressão linear busca ajustar uma relação matemática entre as variáveis
# independentes (x) e a variável alvo (y), minimizando os erros de previsão.

modelo_v2 = linear_model.LinearRegression()

In [35]:
# Treina o modelo
# modelo_v2.fit(x, y)
# Treina (ajusta) o modelo de regressão linear "modelo_v2"
# usando os dados de entrada (x) e a variável alvo (y).
#
# O método .fit():
#   - Calcula os coeficientes da regressão linear.
#   - Encontra a relação matemática que melhor explica
#     como "Modelo", "Kilometragem" e "Idade_Veiculo"
#     influenciam o "Preco_Venda".
#
# Depois desse passo, "modelo_v2" está treinado e pronto para:
#   - Fazer previsões com .predict().
#   - Consultar os coeficientes com .coef_ e o intercepto com .intercept_.
modelo_v2.fit(x,y)

LinearRegression()

In [36]:
# Faz previsões
# modelo_v2.predict(x)
# Usa o modelo de regressão linear "modelo_v2" já treinado
# para gerar previsões da variável alvo (Preco_Venda),
# com base nos dados de entrada (x).
#
# O método .predict():
#   - Aplica os coeficientes e o intercepto calculados no treinamento.
#   - Retorna um array com os valores previstos de "Preco_Venda"
#     para cada linha do DataFrame (cada carro).
#
# Em resumo: você obtém os preços de venda estimados pelo modelo
# a partir das variáveis explicativas (Modelo, Kilometragem, Idade_Veiculo).
modelo_v2.predict(x)

array([21097.26799326, 35669.46519981, 26161.25131906, 40888.38671831,
       30915.35825943, 28747.22473471, 30916.35943266, 23373.3650235 ,
       14794.78029901, 23319.88385735, 17016.39498987, 18255.90053156,
       27144.36164147])

In [37]:
# Calcula a acurácia
# modelo_v2.score(x, y)
# Calcula o coeficiente de determinação R² para o modelo "modelo_v2".
#
# O método .score():
#   - Compara os valores previstos pelo modelo com os valores reais (y).
#   - Retorna o R², que mede a proporção da variância de "Preco_Venda"
#     explicada pelas variáveis independentes (Modelo, Kilometragem, Idade_Veiculo).
#
# Interpretação do R²:
#   - 1.0 → modelo perfeito (explica 100% da variância).
#   - 0.0 → modelo não explica nada além da média.
#   - Valores negativos → modelo pior que simplesmente usar a média.

modelo_v2.score(x,y)

0.8803425650559956

## Aplicando One-Hot-Encoding com Transformer

https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html

https://scikit-learn.org/stable/modules/generated/sklearn.compose.ColumnTransformer.html

In [38]:
# Carrega os dados
dados = pd.read_csv('dados/dataset.csv')
dados

                      Modelo  Kilometragem  Preco_Venda  Idade_Veiculo
0            Jaguar F-Type R         69000        18000              6
1            Jaguar F-Type R         35000        34000              3
2            Jaguar F-Type R         57000        26100              5
3            Jaguar F-Type R         22500        40000              2
4            Jaguar F-Type R         46000        31500              4
5             Mustang Mach 1         59000        29400              5
6             Mustang Mach 1         52000        32000              5
7             Mustang Mach 1         72000        19300              6
8             Mustang Mach 1         91000        12000              8
9   Mercedez Benz AMG GLE 53         67000        22000              6
10  Mercedez Benz AMG GLE 53         83000        20000              7
11  Mercedez Benz AMG GLE 53         79000        21000              7
12  Mercedez Benz AMG GLE 53         59000        33000              5

In [39]:
# from sklearn.preprocessing import OneHotEncoder
#from sklearn.compose import ColumnTransformer

# OneHotEncoder:
#   - Transforma variáveis categóricas em variáveis binárias (dummies).
#   - Exemplo: "Modelo" com categorias ["Sedan", "SUV", "Hatch"]
#     vira colunas extras:
#       Sedan → [1,0,0]
#       SUV   → [0,1,0]
#       Hatch → [0,0,1]

# ColumnTransformer:
#   - Permite aplicar diferentes transformações em diferentes colunas do DataFrame.
#   - Exemplo: aplicar OneHotEncoder na coluna "Modelo"
#     e deixar "Kilometragem" e "Idade_Veiculo" sem transformação.
#
# Isso é útil porque você pode preparar os dados de forma flexível,
# combinando variáveis categóricas (transformadas em dummies)
# com variáveis numéricas (mantidas como estão).

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [40]:
# Cria o encoder com transformação
# OHEncoder = ColumnTransformer(
#    [('Modelo', OneHotEncoder(), [0])],
#    remainder='passthrough'
# )
# Cria um ColumnTransformer chamado "OHEncoder".
#
# O que acontece aqui:
#   - A transformação "Modelo" aplica o OneHotEncoder na coluna de índice 0
#     (ou seja, a primeira coluna da matriz de entrada).
#   - O OneHotEncoder converte categorias em variáveis binárias (dummies).
#   - O parâmetro remainder='passthrough' mantém todas as outras colunas
#     sem transformação (elas passam direto).
#
# Exemplo prático:
#   Se a coluna 0 tiver valores ["Sedan", "SUV", "Hatch"],
#   o OneHotEncoder gera colunas extras:
#     Sedan → [1,0,0]
#     SUV   → [0,1,0]
#     Hatch → [0,0,1]
#
# Enquanto isso, as demais colunas (como Kilometragem e Idade_Veiculo)
# continuam intactas.
OHEncoder = ColumnTransformer([('Modelo', OneHotEncoder(), [0])], remainder = 'passthrough')

In [41]:
# Cópia do dataframe original
df_car = dados

In [42]:
df_car

                      Modelo  Kilometragem  Preco_Venda  Idade_Veiculo
0            Jaguar F-Type R         69000        18000              6
1            Jaguar F-Type R         35000        34000              3
2            Jaguar F-Type R         57000        26100              5
3            Jaguar F-Type R         22500        40000              2
4            Jaguar F-Type R         46000        31500              4
5             Mustang Mach 1         59000        29400              5
6             Mustang Mach 1         52000        32000              5
7             Mustang Mach 1         72000        19300              6
8             Mustang Mach 1         91000        12000              8
9   Mercedez Benz AMG GLE 53         67000        22000              6
10  Mercedez Benz AMG GLE 53         83000        20000              7
11  Mercedez Benz AMG GLE 53         79000        21000              7
12  Mercedez Benz AMG GLE 53         59000        33000              5

In [43]:
# Define os valores de X
# x = df_car.drop('Preco_Venda', axis=1)
# Cria a matriz de variáveis independentes (features) removendo a coluna alvo "Preco_Venda".
#
# O método .drop():
#   - Remove a coluna especificada do DataFrame.
#   - O parâmetro axis=1 indica que estamos removendo uma coluna (não uma linha).
#
# Resultado:
#   - "x" contém todas as colunas explicativas (Modelo, Kilometragem, Idade_Veiculo, etc.).
#   - A coluna "Preco_Venda" é excluída porque ela será usada como variável alvo (y).
#
# Esse é o formato padrão para treinar modelos de Machine Learning:
#   - x → dados de entrada (features)
#   - y → saída/resultado esperado (target)

x = df_car.drop('Preco_Venda', axis = 1)
x

                      Modelo  Kilometragem  Idade_Veiculo
0            Jaguar F-Type R         69000              6
1            Jaguar F-Type R         35000              3
2            Jaguar F-Type R         57000              5
3            Jaguar F-Type R         22500              2
4            Jaguar F-Type R         46000              4
5             Mustang Mach 1         59000              5
6             Mustang Mach 1         52000              5
7             Mustang Mach 1         72000              6
8             Mustang Mach 1         91000              8
9   Mercedez Benz AMG GLE 53         67000              6
10  Mercedez Benz AMG GLE 53         83000              7
11  Mercedez Benz AMG GLE 53         79000              7
12  Mercedez Benz AMG GLE 53         59000              5

In [44]:
# Define os valores de y
# y = df_car['Preco_Venda']
# Define a variável alvo (y) como a coluna "Preco_Venda" do DataFrame "df_car".
#
# Essa coluna contém os valores reais de preço de venda,
# que o modelo tentará prever a partir das variáveis independentes (x).
#
# Agora temos:
#   - x → matriz de features (todas as colunas exceto Preco_Venda).
#   - y → vetor alvo (Preço de Venda).
#
# Esse é o formato padrão para treinar modelos de Machine Learning:
#   x = dados de entrada
#   y = saída/resultado esperado
y = df_car['Preco_Venda']
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Preco_Venda, dtype: int64

In [45]:
# Aplica o encoder ao dataset x
# X = OHEncoder.fit_transform(x)
# Aplica o ColumnTransformer "OHEncoder" sobre os dados de entrada "x".
#
# O método .fit_transform():
#   - "fit" → aprende as categorias presentes na coluna indicada (no caso, "Modelo").
#   - "transform" → converte essa coluna em variáveis binárias (dummies).
#
# Resultado:
#   - "X" será uma matriz NumPy (ou sparse matrix) contendo:
#       • As colunas dummies geradas pelo OneHotEncoder para "Modelo".
#       • As demais colunas (Kilometragem, Idade_Veiculo, etc.) preservadas.
#
# Exemplo:
#   Se "Modelo" tiver categorias ["Sedan", "SUV", "Hatch"],
#   o OneHotEncoder gera colunas extras:
#       Sedan → [1,0,0]
#       SUV   → [0,1,0]
#       Hatch → [0,0,1]
#   E junto disso permanecem os valores numéricos das outras variáveis.
X = OHEncoder.fit_transform(x)
X

array([[1.00e+00, 0.00e+00, 0.00e+00, 6.90e+04, 6.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 3.50e+04, 3.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 5.70e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 2.25e+04, 2.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 4.60e+04, 4.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 5.90e+04, 5.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 5.20e+04, 5.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 7.20e+04, 6.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 9.10e+04, 8.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 6.70e+04, 6.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 8.30e+04, 7.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 7.90e+04, 7.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 5.90e+04, 5.00e+00]])

In [46]:
# Cria a versão 3 do modelo
# from sklearn import linear_model

# modelo_v3 = linear_model.LinearRegression()
# Cria uma nova instância de regressão linear chamada "modelo_v3".
#
# Esse objeto é independente dos modelos anteriores (modelo_v1 e modelo_v2).
# Isso significa que você pode treinar "modelo_v3" com os dados já transformados
# pelo OneHotEncoder (matriz X), sem interferir nos outros modelos.
#
# A regressão linear ajustará uma equação que relaciona as variáveis independentes
# (categorias de "Modelo" transformadas em dummies + Kilometragem + Idade_Veiculo)
# com a variável alvo (Preco_Venda).
modelo_v3 = linear_model.LinearRegression()

In [47]:
# Treina o modelo
# modelo_v3.fit(X, y)
# Treina (ajusta) o modelo de regressão linear "modelo_v3"
# usando os dados de entrada já transformados (X) e a variável alvo (y).
#
# O método .fit():
#   - Calcula os coeficientes da regressão linear considerando
#     as variáveis categóricas convertidas em dummies (via OneHotEncoder)
#     e as variáveis numéricas originais.
#   - Encontra a equação que melhor explica como as variáveis independentes
#     influenciam o "Preco_Venda".
#
# Depois desse passo, "modelo_v3" está treinado e pronto para:
#   - Fazer previsões com .predict(X).
#   - Consultar os coeficientes com .coef_ e o intercepto com .intercept_.
modelo_v3.fit(X,y)

LinearRegression()

In [48]:
# Uma previsão do modelo
# modelo_v3.predict([[0,0,1,45000,4]])
# Usa o modelo de regressão linear "modelo_v3" já treinado
# para prever o preço de venda de um carro com as seguintes características:
#
#   [0, 0, 1, 45000, 4]
#
# Interpretação dos valores:
#   - [0,0,1] → representação OneHotEncoder da categoria "Modelo"
#               (nesse caso, corresponde ao terceiro tipo de modelo cadastrado).
#   - 45000   → valor da quilometragem do veículo.
#   - 4       → idade do veículo em anos.
#
# O método .predict() aplica os coeficientes aprendidos durante o treinamento
# e retorna o preço estimado (em unidades da variável alvo "Preco_Venda").
modelo_v3.predict([[0,0,1,45000,4]])

array([34537.77647335])

In [49]:
# Uma previsão do modelo
# modelo_v3.predict([[0,1,0,86000,7]])
# Usa o modelo de regressão linear "modelo_v3" já treinado
# para prever o preço de venda de um carro com as seguintes características:
#
#   [0, 1, 0, 86000, 7]
#
# Interpretação dos valores:
#   - [0,1,0] → representação OneHotEncoder da categoria "Modelo"
#               (nesse caso, corresponde ao segundo tipo de modelo cadastrado).
#   - 86000   → quilometragem do veículo.
#   - 7       → idade do veículo em anos.
#
# O método .predict() aplica os coeficientes aprendidos durante o treinamento
# e retorna o preço estimado (em unidades da variável alvo "Preco_Venda").
modelo_v3.predict([[0,1,0,86000,7]])

array([17818.95045785])

In [50]:
# Uma previsão do modelo
# modelo_v3.score(X, y)
# Calcula o coeficiente de determinação R² para o modelo "modelo_v3".
#
# O método .score():
#   - Compara os valores previstos pelo modelo com os valores reais (y).
#   - Retorna o R², que mede a proporção da variância de "Preco_Venda"
#     explicada pelas variáveis independentes (X).
#
# Interpretação do R²:
#   - 1.0 → modelo perfeito (explica 100% da variância).
#   - 0.0 → modelo não explica nada além da média.
#   - Valores negativos → modelo pior que simplesmente usar a média.
modelo_v3.score(X,y)

0.9417050937281083

## Salva o Modelo Treinado

In [51]:
# import joblib
# Importa a biblioteca "joblib", usada para salvar e carregar objetos Python.
#
# No contexto de Machine Learning:
#   - Permite salvar modelos treinados (como modelo_v1, modelo_v2, modelo_v3)
#     em arquivos .pkl ou .joblib.
#   - Depois, você pode recarregar esses modelos sem precisar treinar novamente.
#
# Isso é muito útil para:
#   - Reutilizar modelos em diferentes projetos.
#   - Compartilhar modelos já treinados.
#   - Evitar retrabalho e economizar tempo de processamento.

import joblib

In [52]:
# Dump do modelo
# joblib.dump(modelo_v3, 'modelo/modelo_treinado.pkl')
# Salva o objeto "modelo_v3" em um arquivo chamado "modelo_treinado.pkl"
# dentro da pasta "modelo".
#
# O método .dump():
#   - Serializa o modelo treinado (com todos os coeficientes e parâmetros).
#   - Permite que você recarregue esse modelo futuramente sem precisar treinar de novo.
#
# Isso é útil para:
#   - Reutilizar o modelo em outros scripts ou projetos.
#   - Compartilhar o modelo já treinado.
#   - Evitar retrabalho e economizar tempo de processamento.
joblib.dump(modelo_v3,'modelo/modelo_treinado.pkl')

['modelo/modelo_treinado.pkl']

In [ ]:
## Conclusão

Para este conjunto de dados a técnica de One-Hot-Encoding mostrou ser a mais efetiva e deveria ser usada no processamento dos dados para modelagem preditiva.

In [ ]:
# ============================================================
# PROJETO: Análise de Dados Para Traçar Estratégias de Crescimento e Retenção da Base de Clientes
# ============================================================

# Objetivo:
# Este projeto tem como finalidade prever o preço de venda de veículos
# a partir de suas características, utilizando regressão linear.

# ------------------------------------------------------------
# O que o projeto faz:
# ------------------------------------------------------------
# 1. Organização dos dados:
#    - Separa as variáveis independentes (Modelo, Kilometragem, Idade_Veiculo)
#      da variável alvo (Preco_Venda).
#
# 2. Pré-processamento:
#    - Utiliza o OneHotEncoder para transformar a coluna "Modelo"
#      em variáveis binárias (dummies), permitindo que o algoritmo
#      de regressão linear trabalhe com categorias.
#
# 3. Treinamento dos modelos:
#    - Criação de diferentes versões de regressão linear:
#        • Modelos simples com variáveis numéricas.
#        • Modelos expandidos com variáveis categóricas transformadas.
#
# 4. Avaliação de desempenho:
#    - Utiliza o coeficiente de determinação R² para medir
#      o quanto o modelo explica a variância dos preços reais.
#
# 5. Previsões:
#    - Dado um conjunto de características de um carro
#      (modelo, quilometragem e idade), o sistema retorna
#      o preço estimado de venda.
#
# 6. Persistência do modelo:
#    - Usa a biblioteca joblib para salvar o modelo treinado em disco,
#      permitindo reutilização futura sem necessidade de treinar novamente.

# ------------------------------------------------------------
# Em resumo:
# ------------------------------------------------------------
# O projeto é um sistema de previsão de preços de veículos
# baseado em regressão linear. Ele transforma os dados brutos
# em uma matriz adequada para o modelo, treina diferentes versões,
# avalia a performance e gera estimativas de preço.
# Além disso, garante que o modelo possa ser salvo e carregado
# para uso em outros contextos.
# ============================================================

## Conclusão

Para este conjunto de dados a técnica de One-Hot-Encoding mostrou ser a mais efetiva e deveria ser usada no processamento dos dados para modelagem preditiva.

# Fim